name: V-pp-Build and deploy a container to an Azure Web App 

env:
  AZURE_WEBAPP_NAME: backend22  # Nombre de tu aplicación web en Azure
  IMAGE_NAME: esproject         # Nombre base de la imagen Docker
  TAG_NAME: build-tag-1         # Etiqueta personalizada de la imagen Docker

on:
  push:
    branches: [ "main", "develop" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        run: |
          echo "Logging in to Azure Container Registry"
          docker login contreg22.azurecr.io -u contreg22 -p ${{ secrets.DOCKER_REGISTRY_SERVER_PASSWORD }}

      - name: Build Docker image
        run: |
          echo "Building Docker image"
          docker build -t contreg22.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }} -f ./backend/Dockerfile .

      - name: Push Docker image to Azure Container Registry
        run: |
          echo "Pushing Docker image to Azure Container Registry"
          docker push contreg22.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }}

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: 'contreg22.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }}'
